name: .NET

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      allow-publish:
        description: Allow Publishing
        required: true
        default: 'false'
      disable-ubuntu:
        description: Disable Ubuntu Build and Test
        required: false
        default: 'false'
      disable-mac:
        description: Disable Mac Build and Test
        required: false
        default: 'false'
      disable-windows:
        description: Disable Windows Build and Test
        required: false
        default: 'false'
jobs:
  build:
    name: Ubuntu Build and Test
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.disable-ubuntu != 'true' }} # replace with false to disable
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Debug --no-restore --nologo -clp:NoSummary
    - name: Test
      run: dotnet test -c Debug --verbosity normal --no-build --nologo -clp:NoSummary
    - name: Upload Binaries
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: |
          Castaway.Assets/bin/Debug/Castaway.Assets.*.nupkg
          Castaway.Base/bin/Debug/Castaway.Base.*.nupkg
          Castaway.Data/bin/Debug/Castaway.Data.*.nupkg
          Castaway.Input/bin/Debug/Castaway.Input.*.nupkg
          Castaway.Level/bin/Debug/Castaway.Level.*.nupkg
          Castaway.Math/bin/Debug/Castaway.Math.*.nupkg
          Castaway.OpenGL/bin/Debug/Castaway.OpenGL.*.nupkg
          Castaway.OpenGL.Native/bin/Debug/Castaway.OpenGL.Native.*.nupkg
          Castaway.OpenGL.Controllers/bin/Debug/Castaway.OpenGL.Controllers.*.nupkg
          Castaway.Rendering/bin/Debug/Castaway.Rendering.*.nupkg
          Castaway.UI/bin/Debug/Castaway.UI.*.nupkg
  build-mac:
    name: Mac Build and Test
    runs-on: macos-latest
    if: ${{ github.event.inputs.disable-mac != 'true' }} # replace with false to disable
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Debug --no-restore --nologo -clp:"NoSummary;ErrorsOnly"
    - name: Test
      run: dotnet test -c Debug --verbosity normal --no-build --nologo -clp:"NoSummary;ErrorsOnly"
  build-windows:
    name: Windows Build and Test
    runs-on: windows-latest
    if: ${{ github.event.inputs.disable-windows != 'true' }} # replace with false to disable
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Debug --no-restore --nologo -clp:"NoSummary;ErrorsOnly"
    - name: Test
      run: dotnet test -c Debug --verbosity normal --no-build --nologo -clp:"NoSummary;ErrorsOnly"
  publish:
    name: Publish or List
    runs-on: ubuntu-latest
    needs: [build, build-mac, build-windows]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        if: github.event.inputs.allow-publish == 'true'
        with:
          dotnet-version: 6.0.x
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: packages
      - name: List
        if: github.event.inputs.allow-publish != 'true'
        run: ls -Rla | grep .nupkg
      - name: Publish
        if: github.event.inputs.allow-publish == 'true'
        run: |
          dotnet nuget add source --username LiamCoal --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/LiamCoalStudio/index.json
          
          dotnet nuget push Castaway.Assets/bin/Debug/Castaway.Assets.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push Castaway.Base/bin/Debug/Castaway.Base.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push Castaway.Data/bin/Debug/Castaway.Data.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push Castaway.Input/bin/Debug/Castaway.Input.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push Castaway.Level/bin/Debug/Castaway.Level.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push Castaway.Math/bin/Debug/Castaway.Math.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push Castaway.OpenGL/bin/Debug/Castaway.OpenGL.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push Castaway.OpenGL.Native/bin/Debug/Castaway.OpenGL.Native.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push Castaway.OpenGL.Controllers/bin/Debug/Castaway.OpenGL.Controllers.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push Castaway.Rendering/bin/Debug/Castaway.Rendering.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push Castaway.UI/bin/Debug/Castaway.UI.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
